// Hooks
import { useEffect, useState } from "react";
// Libararies
import { Chess } from "chess.js";
// Components
import Head from "next/head";
import GamePanel from "../components/GamePanel";
import Board from "../components/Board";
import History from "../components/History";
// Services
import { getPosition, updatePositionById } from "../lib/positions";

export default function Home() {
  const [game, setGame] = useState(new Chess());
  const [position, setPosition] = useState({});

  const [recording, setRecording] = useState(false);
  const [studying, setStudying] = useState(null);

  const [alerts, setAlerts] = useState([]);
  const [overlay, setOverlay] = useState(null);

  useEffect(() => {
    const getPositionFromDB = async () => {
      const dbPosition = await getPosition({ fen: game.fen() });
      setPosition(dbPosition || {});
    };
    getPositionFromDB();
  }, [game]);

  const handleMove = async (move) => {
    const { san } = move;
    if (recording) {
      if (position._id && !position.book_moves.includes(san)) {
        await updatePositionById({
          id: position._id,
          book_moves: [...position.book_moves, san],
        });
      }
      setRecording(false);
    } else if (studying) {
      if (san === studying) {
        addAlert({ type: "success", message: "Correct!", timeout: 1000 });
      } else {
        addAlert({ type: "danger", message: "Incorrect move!", timeout: 3000 });
      }
    }
    setOverlay(null);
  };

  /**
   * @description Adds an alert to the top of the screen
   * TODO: After timeout remove one alert instead of all.
   * @param {object} alert
   * @param {string} alert.type
   * @param {string} alert.message
   * @param {number} alert.timeout in ms
   */
  const addAlert = ({ type, message, timeout }) => {
    const removeAlert = () => {
      setAlerts([]);
    };
    const alertsCopy = [...alerts];
    alertsCopy.push({ type, message });
    setAlerts(alertsCopy);
    if (timeout) {
      setTimeout(removeAlert, timeout);
    } else {
      setTimeout(removeAlert, 10000);
    }
  };

  /**
   * @description Adds an overlay message to the page
   * @param {object} overlay
   * @param {string} overlay.message - Message to dispaly in overlay
   * @param {number} overlay.timeout - Timeout (ms) to remove the overlay
   */
  const addOverlay = ({ message, timeout }) => {
    const removeOverlay = () => {
      setOverlay(null);
    };
    setOverlay(message);
    if (timeout) {
      setTimeout(removeOverlay, timeout);
    }
  };

  return (
    <>
      <Head>
        <title>Next Chess</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='vh-100'>
        <div className='row h-100 g-0'>
          <div className='d-none d-md-flex col-2'></div>
          <div className='col-12 col-sm-8 col-md-7 d-flex flex-column justify-content-center align-items-center w-board'>
            <div className='d-flex w-100 justify-content-center justify-content-md-start px-2 px-md-0 my-2'>
              <p className='fs-5 m-0'>{position?.name}</p>
            </div>
            <Board game={game} setGame={setGame} onMove={handleMove} />
            <History game={game} setGame={setGame} />
          </div>
          <div className='col-12  col-sm-4 col-md-3 d-flex justify-content-center align-items-center mt-2 flex-fill'>
            <GamePanel
              game={game}
              setGame={setGame}
              position={position}
              setPosition={setPosition}
              recording={recording}
              setRecording={setRecording}
              setStudying={setStudying}
              addOverlay={addOverlay}
              addAlert={addAlert}
            />
          </div>
        </div>
      </main>
      {overlay && (
        <div className='overlay justify-content-center align-items-center'>
          <div className='bg-secondary bg-opacity-50 opacity-75 rounded p-3'>
            <h2>{overlay}</h2>
          </div>
        </div>
      )}
      {alerts.length && (
        <div className='overlay flex-column justify-content-start align-items-center'>
          {alerts.map((alert, idx) => (
            <div
              key={`alert-${idx}`}
              className={`bg-${alert.type} d-flex align-items-center p-2 rounded my-2 bg-opacity-75`}
            >
              <p className='m-0 p-0'>{`${alert.message}`}</p>
            </div>
          ))}
        </div>
      )}
    </>
  );
}
